#!/usr/bin/env ansible-playbook
---
- name: Setup a Persistence Volume (PV)
  hosts: localhost
  connection: local
  vars:
    persistent_volumes:
       - {"type": "tiny",   pv_size: 1,  pv_number: 5 }
       - {"type": "small",  pv_size: 5,  pv_number: 5 }
       - {"type": "normal", pv_size: 10, pv_number: 5 }
       - {"type": "big",    pv_size: 20, pv_number: 5 }
       - {"type": "large",  pv_size: 25, pv_number: 5 }
    pv_number: 20
    pv_size  : 5Gi
    nfs_server: 192.168.0.100
    nfs_path_prefix  : /var/storage/local
  tasks:
    - name: Create all the necessary directories
      file: path={{ nfs_path_prefix }}{{ item }} group=nfsnobody owner=nfsnobody mode=777 state=directory recurse=yes
      with_sequence: start=1 end={{ pv_number }}
      tags:
         - create

    - name: Create all the necessary information in /etc/exports
      template: src=templates/exports.j2 dest=/etc/exports

    - name: Add the following lines into the IPTables rules for NFS
      lineinfile: dest=/etc/sysconfig/iptables state=present insertbefore="COMMIT" line="{{ item }}"
      with_items: 
         - "-A OS_FIREWALL_ALLOW -p tcp -m state --state NEW -m tcp --dport 111 -j ACCEPT"
         - "-A OS_FIREWALL_ALLOW -p tcp -m state --state NEW -m tcp --dport 2049 -j ACCEPT"
         - "-A OS_FIREWALL_ALLOW -p tcp -m state --state NEW -m tcp --dport 20048 -j ACCEPT"
         - "-A OS_FIREWALL_ALLOW -p tcp -m state --state NEW -m tcp --dport 50825 -j ACCEPT"
         - "-A OS_FIREWALL_ALLOW -p tcp -m state --state NEW -m tcp --dport 53248 -j ACCEPT"
      tags: iptables

    - name: Restart IPTables Service
      service: name=iptables state=restarted
      notify: Restart IPTables Service
      tags: iptables

    - name: Modify information into NFS file
      lineinfile: dest=/etc/sysconfig/nfs state=present regexp={{ item.regex }} line={{ item.option }}
      with_items:
         - { regex: "^RPCMOUNTDOPTS", option: "RPCMOUNTDOPTS=\"-p 20048\""}
         - { regex: "^STATDARG",      option: "STATDARG=\"-p 50825\""}

# Bug according to: https://access.redhat.com/solutions/2200331
#    - name: Modify information on sysctl
#      lineinfile: dest=/etc/sysctl.conf state=present line={{ item }}
#      with_items:
#         - "fs.nfs.nlm_tcpport=53248"
#         - "fs.nfs.nlm_udpport=53248"
#
#    - name: Persist the changes for sysctl
#      command: sysctl -p

    - name: Restart all the necessary services related to NFS
      service: name={{ item }}  state=restarted enabled=true
      with_items:
         - rpcbind
         - nfs-server
         - nfs-lock 
         - nfs-idmap
     
    - name: Template all the necessary Persistent Volumes in a temporary directory
      template: src=templates/persistentvolume.yaml.j2 dest=/tmp/persistentvolume.yaml

    - name: Change to administrator user in OpenShift
      command: oc login --username=system:admin

    - name: Create the PV's from a temporary directory
      command: oc create -f /tmp/persistentvolume.yaml

  handlers:
    - name: Restart IPTables Service
      service: name=iptables state=restarted
